version: '3.0'

services:
  app:
    build: .
    container_name: tracepoint-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    #  - ./app/node_modules # Deu bronca aí eu comentei
    env_file:
      - .env
    depends_on:
      - db
    command: ["bash", "-c", "./wait-for-it.sh db:5432 -- npm run migration:run && npm run dev"]
  
  db:
    image: postgres:15
    container_name: tracepoint-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trace_point
    ports:
      - "5000-5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: tracepoint-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  pgdata:
